substitutions:
  name: m5stack-atom-echo-bcfaf0
  friendly_name: M5Stack Atom Echo bcfaf0
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qfv9HgTS6K9Eazeu8lRF7gUDrjpw609V4NBhGLR5TUs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
